version: "3.5"

services:
  web:
    image: webdevops/php-nginx:7.3
    working_dir: /app
    ports:
      - 81:80
    depends_on:
      - database
    volumes:
      - .:/app
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      WEB_DOCUMENT_INDEX: index.php
      PHP_DATE_TIMEZONE: "Europe/Paris"
      PHP_DISPLAY_ERRORS: 1

  database:
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - 'mysql_data:/var/lib/mysql'
    environment:
      MYSQL_DATABASE: symfonyweb
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - database
    ports:
      - 8081:80
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: database

volumes:
  mysql_data:
    driver: local
